#!/bin/zsh
# Build obs-stereo-splat WITHOUT Xcode: plain clang -bundle against the
# OBS 32.x libobs headers, -undefined dynamic_lookup (symbols resolve in
# the host OBS process at load), hand-assembled .plugin bundle, ad-hoc
# codesign, installed to the user plugin directory.
#
# The obs-plugintemplate's CMake hard-requires the Xcode generator
# (cmake/macos/compilerconfig.cmake) — this machine has only the CLT, so
# the template is used for layout/source only.
set -euo pipefail
cd "$(dirname "$0")"

OBS_TAG="32.1.2"
HDRS="obs-headers"
BUILD="build_manual"
NAME="obs-stereo-splat"
PLUG="$BUILD/$NAME.plugin"
INSTALL_DIR="$HOME/Library/Application Support/obs-studio/plugins"

# --- headers ---------------------------------------------------------
if [[ ! -d "$HDRS" ]]; then
    git clone --depth 1 --branch "$OBS_TAG" \
        https://github.com/obsproject/obs-studio.git "$HDRS"
fi
# obsconfig.h is normally generated by the OBS build; a module compile
# only needs these definitions.
if [[ ! -f "$HDRS/libobs/obsconfig.h" ]]; then
    cat > "$HDRS/libobs/obsconfig.h" <<EOF
#pragma once
#define OBS_VERSION "$OBS_TAG"
#define OBS_VERSION_CANONICAL "$OBS_TAG"
#define OBS_DATA_PATH "../../data"
#define OBS_INSTALL_PREFIX ""
#define OBS_PLUGIN_DESTINATION "obs-plugins"
#define OBS_RELATIVE_PREFIX "../../"
#define OBS_RELEASE_CANDIDATE 0
#define OBS_BETA 0
EOF
fi

# --- compile ---------------------------------------------------------
mkdir -p "$BUILD"
clang -bundle -arch arm64 -mmacosx-version-min=12.0 -O2 \
    -std=c17 -fvisibility=hidden \
    -I "$HDRS/libobs" -I src -I /opt/homebrew/include \
    src/plugin-main.c src/stereo-splat.c src/plugin-support.c \
    -undefined dynamic_lookup -framework OpenGL \
    -o "$BUILD/$NAME"

# --- bundle ----------------------------------------------------------
rm -rf "$PLUG"
mkdir -p "$PLUG/Contents/MacOS" "$PLUG/Contents/Resources"
cp "$BUILD/$NAME" "$PLUG/Contents/MacOS/$NAME"
cp -R data/ "$PLUG/Contents/Resources/"
cat > "$PLUG/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key><string>$NAME</string>
    <key>CFBundleIdentifier</key><string>com.sublingualism.obs-stereo-splat</string>
    <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
    <key>CFBundleName</key><string>$NAME</string>
    <key>CFBundlePackageType</key><string>BNDL</string>
    <key>CFBundleShortVersionString</key><string>0.1.0</string>
    <key>CFBundleVersion</key><string>0.1.0</string>
    <key>CFBundleSupportedPlatforms</key><array><string>MacOSX</string></array>
    <key>LSMinimumSystemVersion</key><string>12.0</string>
</dict>
</plist>
EOF
codesign --force --deep -s - "$PLUG"

# --- install ---------------------------------------------------------
mkdir -p "$INSTALL_DIR"
rm -rf "$INSTALL_DIR/$NAME.plugin"
cp -R "$PLUG" "$INSTALL_DIR/"
echo "installed: $INSTALL_DIR/$NAME.plugin"
echo "relaunch OBS (and restart the bridge) to load it"
